# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chakshu/CLionProjects/Local-Collision-Differential-Attack-on-Reduced-SHA-256-upto-24-Rounds

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chakshu/CLionProjects/Local-Collision-Differential-Attack-on-Reduced-SHA-256-upto-24-Rounds

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chakshu/CLionProjects/Local-Collision-Differential-Attack-on-Reduced-SHA-256-upto-24-Rounds/CMakeFiles /home/chakshu/CLionProjects/Local-Collision-Differential-Attack-on-Reduced-SHA-256-upto-24-Rounds/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chakshu/CLionProjects/Local-Collision-Differential-Attack-on-Reduced-SHA-256-upto-24-Rounds/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 22-attack

# Build rule for target.
22-attack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 22-attack
.PHONY : 22-attack

# fast build rule for target.
22-attack/fast:
	$(MAKE) -f CMakeFiles/22-attack.dir/build.make CMakeFiles/22-attack.dir/build
.PHONY : 22-attack/fast

#=============================================================================
# Target rules for targets named 24-attack

# Build rule for target.
24-attack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 24-attack
.PHONY : 24-attack

# fast build rule for target.
24-attack/fast:
	$(MAKE) -f CMakeFiles/24-attack.dir/build.make CMakeFiles/24-attack.dir/build
.PHONY : 24-attack/fast

Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.o: Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.o

.PHONY : Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.o

# target to build an object file
Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.o:
	$(MAKE) -f CMakeFiles/22-attack.dir/build.make CMakeFiles/22-attack.dir/Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.o
.PHONY : Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.o

Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.i: Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.i

.PHONY : Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.i

# target to preprocess a source file
Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.i:
	$(MAKE) -f CMakeFiles/22-attack.dir/build.make CMakeFiles/22-attack.dir/Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.i
.PHONY : Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.i

Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.s: Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.s

.PHONY : Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.s

# target to generate assembly for a file
Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.s:
	$(MAKE) -f CMakeFiles/22-attack.dir/build.make CMakeFiles/22-attack.dir/Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.s
.PHONY : Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.c.s

Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.o: Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.o

.PHONY : Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.o

# target to build an object file
Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.o:
	$(MAKE) -f CMakeFiles/24-attack.dir/build.make CMakeFiles/24-attack.dir/Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.o
.PHONY : Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.o

Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.i: Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.i

.PHONY : Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.i

# target to preprocess a source file
Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.i:
	$(MAKE) -f CMakeFiles/24-attack.dir/build.make CMakeFiles/24-attack.dir/Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.i
.PHONY : Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.i

Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.s: Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.s

.PHONY : Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.s

# target to generate assembly for a file
Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.s:
	$(MAKE) -f CMakeFiles/24-attack.dir/build.make CMakeFiles/24-attack.dir/Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.s
.PHONY : Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 22-attack"
	@echo "... 24-attack"
	@echo "... Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.o"
	@echo "... Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.i"
	@echo "... Deterministic_22_Round_Differential_Attack_on_SHA-256/22_round_attack_sha_256.s"
	@echo "... Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.o"
	@echo "... Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.i"
	@echo "... Probabilistic_24_Round_Differential_Attack_on_SHA-256/24_round_attack_sha_256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

